# Generated by Django 3.0.6 on 2020-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200516_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='registration_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='registration_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
