# Generated by Django 3.0.6 on 2020-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='Expected_recovery_date',
        ),
        migrations.AlterField(
            model_name='diseases',
            name='recoveryperiod',
            field=models.IntegerField(blank=True),
        ),
    ]
