# Generated by Django 3.0.6 on 2020-05-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20200517_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
