# Generated by Django 3.0.6 on 2020-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20200517_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='Expected_recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
