# Generated by Django 3.0.6 on 2020-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_auto_20200517_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='precautions',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
