# Generated by Django 3.0.7 on 2020-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0011_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='ques',
        ),
        migrations.AddField(
            model_name='answer',
            name='ans',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
