# Generated by Django 3.0.7 on 2020-06-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0012_auto_20200608_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ques',
            new_name='question',
        ),
    ]
