# Generated by Django 3.0.7 on 2020-06-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0014_remove_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(max_length=10),
        ),
    ]
