# Generated by Django 3.0.7 on 2020-06-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0015_auto_20200609_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer',
        ),
    ]
