# Generated by Django 3.0.7 on 2020-06-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0017_auto_20200609_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q2',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='q3',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='q4',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='q5',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='q6',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
